### ISSUE TITLE
saveDevice with additionalInfo

### ISSUE THREAD

**Issue by BlackByteDE** [nepton/Thingsboard.Net#1]
Hi,

i've testing around with your project. I stumbled only about one issue. I could not save a device with additionalInfos.
I think there is no way i could add following to the save process.
`"additionalInfo": {
        "gateway": true
}`

In the thingsboard api docu its and the end of the example [thinkboardLink](https://demo.thingsboard.io/swagger-ui/#/device-controller/saveDeviceUsingPOST)

Hope you could help.

**Comment by nepton** [comment]
Publish v3.4.11

Add new feature:
You can set / get IsGateway property or AdditionalInfo property in TbNewDevice or TbDevice 

```csharp
TbNewDevice device = new();
device.IsGateway = true; // or device.AdditionalInfo["gateway"] = true;
```

Leave a comment if you have any questions or suggestions.

**Comment by nepton** [comment]
Leave a comment if you have any questions or suggestions about this issue.
