### ISSUE TITLE
AssetProfile API missing

### ISSUE THREAD

**Issue by ThomasPrioul** [nepton/Thingsboard.Net#3]
**Is your feature request related to a problem? Please describe.**
There isn't a built-in device profile API client, this API exists in TB 3.4.4.

**Describe the solution you'd like**
Add a method to FlurlTbClientFactory to access the assetprofile client.

**Describe alternatives you've considered**
Manually using a client for now.

![image](https://user-images.githubusercontent.com/15314924/233033264-530c5ebf-cdd3-4cd1-bd47-319e457c5e2f.png)

**Comment by nepton** [comment]
Thank you for your PR :)
